### ISSUE TITLE
host interface networking driver

### ISSUE THREAD

**Issue by gabrieligbastos** [felix-centenera/OKD3.9_CentOS7.5_CNS-6VMs#1]
Hey, first congrats for the project, it seems really nice.

I've been having issues to deploy it,
Here is the error. can you help me?

```
Progress state: E_FAIL
VBoxManage.EXE: error: Failed to create the host-only adapter
VBoxManage.EXE: error: Could not find Host Interface Networking driver! Please reinstall
VBoxManage.EXE: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.EXE: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
```

**Comment by anibal-aguila** [comment]
Hi @gabrieligbastos, I have a forked version whit some changes on this repo, please could you try it or wait until @felix-centenera accept the pull-request?

https://github.com/wtmh-dev/OKD3.9_CentOS7.5_CNS

:cheers:

**Comment by felix-centenera** [comment]
Hi. Thanks both of you to forK the project and the suggestions.  @anibal-aguila I will approve the changes just with a little change that I have commented in the pull request, have a look and tell me ;)
@gabrieligbastos, it looks like  you have a problem with Vagrant in Windows, have you been able to resolved? It looks to me to like a conflict with another Vms.

**Comment by felix-centenera** [comment]
VBoxManage.EXE: It is an error due to Windows Vagrant. This project is focused on Linux.
